import type {
  CollectionCategory,
  CollectionDisplay,
  ElementDisplay,
  EntryDisplay,
} from "@/types/element";
import {
  type CollectionType,
  Color,
  type ElementType,
  type EntryType,
} from "@prisma/client";
import {
  Briefcase,
  Folder,
  Box,
  FileText,
  Users,
  BookOpen,
  CheckSquare,
  Bug,
  MessageSquare,
  MessageCircle,
  Calendar,
  HardDrive,
  FileIcon,
  StickyNote,
  ListTodo,
  AlertCircle,
  Hash,
  Tv,
  CalendarDays,
  File,
  HelpCircle,
  Bell,
} from "lucide-react";

// Collection Categories
export const COLLECTION_CATEGORIES: Record<string, CollectionCategory> = {
  GENERAL: {
    name: "General",
    description: "Basic content and organization",
    icon: Box,
    color: Color.INDIGO,
  },
  PRODUCTIVITY: {
    name: "Productivity",
    description: "Tools for getting work done",
    icon: CheckSquare,
    color: Color.BLUE,
  },
  COMMUNICATION: {
    name: "Communication",
    description: "Collaboration and messaging tools",
    icon: MessageCircle,
    color: Color.GREEN,
  },
  KNOWLEDGE: {
    name: "Knowledge",
    description: "Documentation and information storage",
    icon: BookOpen,
    color: Color.PURPLE,
  },
  STORAGE: {
    name: "Storage",
    description: "File and resource management",
    icon: HardDrive,
    color: Color.GRAY,
  },
};

// Element Type Displays
export const ELEMENT_DISPLAYS: Record<ElementType, ElementDisplay> = {
  Workspace: {
    name: "workspace",
    label: "Workspace",
    description: "A collaborative environment for teams and projects",
    icon: Briefcase,
    color: Color.BLUE,
    type: "Workspace",
  },
  Folder: {
    name: "folder",
    label: "Folder",
    description: "Organize your content with folders",
    icon: Folder,
    color: Color.YELLOW,
    type: "Folder",
  },
  Collection: {
    name: "collection",
    label: "Collection",
    description: "A container for related entries",
    icon: Box,
    color: Color.PURPLE,
    type: "Collection",
  },
  Entry: {
    name: "entry",
    label: "Entry",
    description: "Individual content item",
    icon: FileText,
    color: Color.GRAY,
    type: "Entry",
  },
  Team: {
    name: "team",
    label: "Team",
    description: "A group of collaborating members",
    icon: Users,
    color: Color.GREEN,
    type: "Team",
  },
};

// Collection Type Displays
export const COLLECTION_DISPLAYS: Record<CollectionType, CollectionDisplay> = {
  Notebook: {
    name: "notebook",
    label: "Notebook",
    description: "Collection of pages and notes for documentation",
    icon: BookOpen,
    color: Color.BLUE,
    type: "Notebook",
    category: COLLECTION_CATEGORIES.KNOWLEDGE,
  },
  TaskGroup: {
    name: "taskgroup",
    label: "Task Group",
    description: "Organize and track tasks and to-dos",
    icon: CheckSquare,
    color: Color.GREEN,
    type: "TaskGroup",
    category: COLLECTION_CATEGORIES.PRODUCTIVITY,
  },
  IssueTracker: {
    name: "issuetracker",
    label: "Issue Tracker",
    description: "Track bugs, issues, and technical problems",
    icon: Bug,
    color: Color.RED,
    type: "IssueTracker",
    category: COLLECTION_CATEGORIES.PRODUCTIVITY,
  },
  Discussion: {
    name: "discussion",
    label: "Discussion",
    description: "Forum-style conversations and topics",
    icon: MessageSquare,
    color: Color.PURPLE,
    type: "Discussion",
    category: COLLECTION_CATEGORIES.COMMUNICATION,
  },
  Chat: {
    name: "chat",
    label: "Chat",
    description: "Real-time messaging and channels",
    icon: MessageCircle,
    color: Color.TEAL,
    type: "Chat",
    category: COLLECTION_CATEGORIES.COMMUNICATION,
  },
  Calendar: {
    name: "calendar",
    label: "Calendar",
    description: "Schedule events and manage time",
    icon: Calendar,
    color: Color.ORANGE,
    type: "Calendar",
    category: COLLECTION_CATEGORIES.PRODUCTIVITY,
  },
  Storage: {
    name: "storage",
    label: "Storage",
    description: "File storage and document management",
    icon: HardDrive,
    color: Color.GRAY,
    type: "Storage",
    category: COLLECTION_CATEGORIES.STORAGE,
  },
  FAQ: {
    name: "faq",
    label: "FAQ",
    description: "Frequently asked questions and answers",
    icon: HelpCircle,
    color: Color.CYAN,
    type: "FAQ",
    category: COLLECTION_CATEGORIES.KNOWLEDGE,
  },
  Announcement: {
    name: "announcement",
    label: "Announcement",
    description: "Important announcements and alerts",
    icon: Bell,
    color: Color.ORANGE,
    type: "Announcement",
    category: COLLECTION_CATEGORIES.GENERAL,
  },
};

// Entry Type Displays
export const ENTRY_DISPLAYS: Record<EntryType, EntryDisplay> = {
  Page: {
    name: "page",
    label: "Page",
    description: "Rich text document or wiki page",
    icon: FileText,
    color: Color.BLUE,
    type: "Page",
    collection: "Notebook",
  },
  Note: {
    name: "note",
    label: "Note",
    description: "Quick note or memo",
    icon: StickyNote,
    color: Color.YELLOW,
    type: "Note",
    collection: "Notebook",
  },
  Task: {
    name: "task",
    label: "Task",
    description: "Individual task or to-do item",
    icon: ListTodo,
    color: Color.GREEN,
    type: "Task",
    collection: "TaskGroup",
  },
  Issue: {
    name: "issue",
    label: "Issue",
    description: "Bug report or technical issue",
    icon: AlertCircle,
    color: Color.RED,
    type: "Issue",
    collection: "IssueTracker",
  },
  Thread: {
    name: "thread",
    label: "Thread",
    description: "Discussion thread or conversation",
    icon: MessageSquare,
    color: Color.PURPLE,
    type: "Thread",
    collection: "Discussion",
  },
  Channel: {
    name: "channel",
    label: "Channel",
    description: "Chat channel or room",
    icon: Hash,
    color: Color.TEAL,
    type: "Channel",
    collection: "Chat",
  },
  Event: {
    name: "event",
    label: "Event",
    description: "Calendar event or appointment",
    icon: CalendarDays,
    color: Color.ORANGE,
    type: "Event",
    collection: "Calendar",
  },
  File: {
    name: "file",
    label: "File",
    description: "Uploaded file or attachment",
    icon: File,
    color: Color.GRAY,
    type: "File",
    collection: "Storage",
  },
  Question: {
    name: "question",
    label: "Question",
    description: "Frequently asked question with answer",
    icon: HelpCircle,
    color: Color.CYAN,
    type: "Question",
    collection: "FAQ",
  },
  Alert: {
    name: "alert",
    label: "Alert",
    description: "Important announcement or notification",
    icon: Bell,
    color: Color.ORANGE,
    type: "Alert",
    collection: "Announcement",
  },
};
